### ISSUE TITLE
Review xrefs

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#1]
### What part of the schema is being reviewed?

![image](https://user-images.githubusercontent.com/112839/48261162-02ab6300-e416-11e8-906f-ec194939a6bb.png)

https://github.com/VirtualFlyBrain/VFB_json_schema/blob/master/json_schema/vfb_termInfo.json#L267

![image](https://user-images.githubusercontent.com/112839/48261680-c6790200-e417-11e8-976f-46d78b2c6b5a.png)

https://github.com/VirtualFlyBrain/VFB_json_schema/blob/master/json_schema/vfb_termInfo.json#L99

![image](https://user-images.githubusercontent.com/112839/48261181-18208d00-e416-11e8-984b-73907607626a.png)

### What is the intended usage/context of this part_of the schema?

xrefs is intended for specifying a list of links from TermInfo to third-party sites.  Each link needs text & a hyperlink.  It can optionally include an icon with the logo of the third party site.

#### Examples include:

* Links from classes other sites that reference that class - or something closely corresponding to it. e.g. Links from larval anatomy classes to the larval atlas

* Links from data to a data source, e.g. links from anatomical individuals to the same individual on a third-party site, e.g. links to FlyLight for Janelia light-level data ora CATMAID instance for EM reconstructions.

* Links from data to some third party site that hosts the same data - e.g. links to FlyCircuit data on  FFBO 

### Questions for reviewers 

If the answer to any question is no, please suggest improvements.

1. Are the names of properties intuitive and consistent?
1. Does the structure work to capture relationships between elements?
1. Is the internal documentation (description field content) sufficient?
1. Does this list of required fields make sense?
1. Is there any content missing?

**Comment by dosumis** [comment]
*1. Are the names of properties intuitive and consistent?*

I'm not sure about xrefs as this could be broader (including references to entities in DBs for which we have no hyperlink).  Perhaps 'linkOuts'?

*2. Is the internal documentation (description field content) sufficient?

I think it could be improved.  The top level should have a description.

**Comment by matentzn** [comment]
Names and descriptions of properties, suggestions:
* xref
  * link: A URL linking to some third party **_resource_**. [resource instead of site, to avoid any mix up with the site url in site: key, maybe even consider to use link_resource instead of just link, to further distance from the site:]
  * link_text: [link_label might be more accurate, but no strong feeling]
  * site: [all clear]

I dont mind so much else re labels and descriptions. Maybe a single comment for the top level, but I dont find it necessary.

**Comment by matentzn** [comment]
Can you remind me what the use case for having the short form in the minimal entity info is? Rather than, say, qsl or curie?

**Comment by dosumis** [comment]
I understand why curies are safer, but short_form is what the Geppetto model uses, so is essential for current functioning + we don't have qsl in PDB and we don't (reliably) have curies in there either.   We can easily extend the minimal entity infor once we have v2 of pdb.  But if we want to change Geppetto to use curies in future, then this will require careful co-ordination with work on Geppetto.  @Robbie1977  - any comment on this?

**Comment by dosumis** [comment]
From discussion with Nico:

Icon -> site_icon
