### ISSUE TITLE
implement hiding relationship edges in term info

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_json_schema#109]
look for hide_in_terminfo = TRUE on relationship edges
related to #108

**Comment by dosumis** [comment]
https://github.com/VirtualFlyBrain/VFB_json_schema/blob/master/src/vfb_query_builder/query_roller.py#L231

**Comment by hkir-dev** [comment]
duplicate with https://github.com/VirtualFlyBrain/VFB_json_schema/issues/115
