### ISSUE TITLE
add scRNAseq queries to VFB _JSON schema ( and from there to XMI)

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_json_schema#112]
query for genes in a cluster
`MATCH (c:Cluster)-[e:expresses]->(g:Gene) 
WHERE c.short_form="FBlc0004872" 
RETURN g.label, labels(g), e.expression_level[0], e.expression_extent[0] 
ORDER BY e.expression_extent[0] DESCENDING`

query for clusters of a cell type
`MATCH (ds:DataSet)<-[:has_source]-(c:Cluster)-[:composed_primarily_of]->(a:Anatomy:Class)-[:SUBCLASSOF*..]->(b:Anatomy:Class)
WHERE (a.short_form="FBbt_00058207") OR (b.short_form="FBbt_00058207")
RETURN c.label, a.label, ds.label`

**Comment by dosumis** [comment]
Tables to support

![image](https://user-images.githubusercontent.com/112839/196643135-57d088cc-9ab8-4f64-ab7a-d97e3a7e738b.png)

To consider: 
- How does this fit with the SOLR caching model for queries?
- Better to show cell type in expression report (could be in header, but probably easier to achieve in table for now).

**Comment by dosumis** [comment]
The genes expressed in  cluster query will never explode - at most it would have rows in the thousands, so it could be precached - indexed on cluster ID

**Comment by Robbie1977** [comment]
```MATCH (ds:scRNAseq_DataSet:Individual)<-[:has_source]-(c:Cluster)-[:composed_primarily_of]->(a:Anatomy:Class) RETURN c.label, a.label, ds.label```
7ms

**Comment by Robbie1977** [comment]
```MATCH (primary:Individual) WHERE primary.short_form in ['FBlc0003977']  
WITH primary 
OPTIONAL MATCH (primary)<-[:depicts]-(channel:Individual)-[irw:in_register_with]->(template:Individual)-[:depicts]->(template_anat:Individual) WITH template, channel, template_anat, irw, primary   OPTIONAL MATCH (channel)-[:is_specified_output_of]->(technique:Class)  
WITH CASE WHEN channel IS NULL THEN [] ELSE collect ({ channel: { short_form: channel.short_form, label: coalesce(channel.label,''), iri: channel.iri, types: labels(channel), unique_facets: apoc.coll.sort(coalesce(channel.uniqueFacets, [])), symbol: coalesce(([]+channel.symbol)[0], '')} , imaging_technique: { short_form: technique.short_form, label: coalesce(technique.label,''), iri: technique.iri, types: labels(technique), unique_facets: apoc.coll.sort(coalesce(technique.uniqueFacets, [])), symbol: coalesce(([]+technique.symbol)[0], '')} ,image: { template_channel : { short_form: template.short_form, label: coalesce(template.label,''), iri: template.iri, types: labels(template), unique_facets: apoc.coll.sort(coalesce(template.uniqueFacets, [])), symbol: coalesce(([]+template.symbol)[0], '')} , template_anatomy: { short_form: template_anat.short_form, label: coalesce(template_anat.label,''), iri: template_anat.iri, types: labels(template_anat), unique_facets: apoc.coll.sort(coalesce(template_anat.uniqueFacets, [])), symbol: coalesce(([]+template_anat.symbol)[0], '')} ,image_folder: COALESCE(([]+irw.folder)[0], ''), index: coalesce(apoc.convert.toInteger(([]+irw.index)[0]), []) + [] }}) END AS channel_image,primary 
OPTIONAL MATCH (primary)-[:INSTANCEOF]->(typ:Class)  
WITH CASE WHEN typ is null THEN [] ELSE collect ({ short_form: typ.short_form, label: coalesce(typ.label,''), iri: typ.iri, types: labels(typ), unique_facets: apoc.coll.sort(coalesce(typ.uniqueFacets, [])), symbol: coalesce(([]+typ.symbol)[0], '')} ) END AS types,primary,channel_image RETURN { core : { short_form: primary.short_form, label: coalesce(primary.label,''), iri: primary.iri, types: labels(primary), unique_facets: apoc.coll.sort(coalesce(primary.uniqueFacets, [])), symbol: coalesce(([]+primary.symbol)[0], '')} , description : coalesce(primary.description, []), comment : coalesce(primary.comment, []) } AS term, 'c15d2fd' AS version , channel_image, types```

**Comment by dosumis** [comment]
Plan:

Cache SOLR documents with sufficient info per line. 

`<Some standard dataset query here>-(c:Cluster)-[:composed_primarily_of]->(a:Anatomy:Class:Cell) RETURN < some standard return clause here>`

Query on site then runs OWLERY query for all subclasses of query term --> SOLR query.


Subclauses:
 - We don't currently show dataset information in any results tables, so it may be overkill to use a standard dataset query.
 - New subcluster query needs standard return clause.  Use core (min) for anatomy and cluster.


TODO: Write a new function in QueryLibraryCore that starts from the anatomical class:

**Comment by dosumis** [comment]
@Robbie1977 @Clare72 Can this be closed? I believe the queries it described as live?
