### ISSUE TITLE
Add query & subschema  to template.json for driving stack browser & canvas.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#16]
Every time a new template is chosen for display, we need a new chunk of JSON to drive it.

This consists of metadata about all the painted domains on a stack.  We can potentially find these by querying

template_channel < - [irw:in_register_with]-Do - 

Current JSON driving stack browser looks like this:

```json
{  
    "indexNumber":0,
    "serverUrl":"https://www.virtualflybrain.org/fcgi/wlziipsrv.fcgi",
    "fileLocation":"/disk/data/VFB/IMAGE_DATA/VFB/i/0001/7894//volume.wlz",
    "subDomains":[ 
        [ $(Voxel Size) ],
        [ $(Domain VFBid) ],
        [ $(label - for floatover) ],
        [ $(Domain ClassId) ],
        [ $(centre point "[x,y,z]") ]
    ]
}
```

Robbie notes:  subDomains list index = domain index.

Better to clean this up with explicit keys & including for domain_index rather than rely on parallel lists?
@Robbie1977 - please comment.  Understandable if you want to avoid churn.

All info about subdomains can be pulled from neo (where present) except Voxel size? (@Robbie1977  - comments?)

Presumably server URL should come from some generic config?  

fileLocation could be munged from template short_form.  Should it be?

**Comment by dosumis** [comment]
Should we call this template.json?  Do we also need a template json for term info?

**Comment by dosumis** [comment]
@Robbie1977  - is this done?

**Comment by Robbie1977** [comment]
yes
