### ISSUE TITLE
template schema

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#18]
### What part of the schema is being reviewed?

Anatomical individual - with the following extra subschemas.

![image](https://user-images.githubusercontent.com/112839/50350170-2645eb00-0536-11e9-9afc-e063b62fd499.png)
![image](https://user-images.githubusercontent.com/112839/50350198-44abe680-0536-11e9-8ced-9bdfaddceed1.png)

### What is the intended usage/context of this part_of the schema?

When a new template is chosen, we need information about the template and painted domains in order to drive the canvas and stack browser.

### Questions for reviewers 

If the answer to any question is no, please suggest improvements.

1. Are the names of properties intuitive and consistent?
1. Does the structure work to capture relationships between elements?
1. Is the internal documentation (description field content) sufficient?
1. Does this list of required fields make sense?
1. Is there any content missing?

**Comment by dosumis** [comment]
* Are the names of properties intuitive and consistent?
   
Property names (& structure) are inconsistent with those used for anatomy_channel_template (used for regular images)

![image](https://user-images.githubusercontent.com/112839/50350335-c3088880-0536-11e9-9c26-d0f2f5f7bbc0.png)

These should be aligned as far as possible

Suggested solution: 

Standardise names for anatomical_individuals,  anatomical_types, channels and (image)_folder 

suggest:
anatomical_individual;
anatomical_type
channel
image_folder

* Does the structure work to capture relationships between elements?

Yes - safe to assume 1:1 between anatomical type and individual in this case.  However, it is not consistent with the structure for other images (see above).  Can these be aligned further?

* Is the internal documentation (description field content) sufficient?

No - there's not much of this.

* Does this list of required fields make sense?

Yes.

*  Is there any content missing?

Domain channels are not present - although they are likely not currently needed.

**Comment by Robbie1977** [comment]
Getting license returned in place of dataset:
```
"dataset_license":[  
      {  
         "dataset":{  
            "link":"",
            "core":{  
               "short_form":"VFBlicense_CC_BY_NC_SA_4_0",
               "label":"CC-BY-NC-SA_4.0",
               "iri":"http://creativecommons.org/licenses/by-nc-sa/4.0",
               "types":[  
                  "Individual",
                  "License"
               ]
            }
         },
         "license":{  
            "icon":"http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png",
            "link":"https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode",
            "core":{  
               "short_form":"VFBlicense_CC_BY_NC_SA_4_0",
               "label":"CC-BY-NC-SA_4.0",
               "iri":"http://creativecommons.org/licenses/by-nc-sa/4.0",
               "types":[  
                  "Individual",
                  "License"
               ]
            }
         }
      }
   ]
```

**Comment by Robbie1977** [comment]
After new query: https://github.com/VirtualFlyBrain/geppetto-vfb/commit/8a722d9e3b87e6f84f13a8e3ec13cd8b600a92ef 
Error in: ```WITH COLLECT ({ dataset: { link : coalesce(l.dataset_link, ''), core : { short_form: l.short_form, label: coalesce(l.label,''), iri: l.iri, types: labels(l) }  }, license: { icon : coalesce(l.license_logo, ''), link : coalesce(l.license_url, ''), core : { short_form: l.short_form, label: coalesce(l.label,''), iri: l.iri, types: labels(l) }  }}) AS dataset_license``` using l instrad of ds in dataset:

**Comment by dosumis** [comment]
@Robbie1977 As this is now in use, can I assume it is fit for purpose?  Or do I need to make sure direct edits to the XMI make it back into the query generation code?

**Comment by Robbie1977** [comment]
yep
