### ISSUE TITLE
Expression_pattern terminfo query needed

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_json_schema#34]
Class:Expression_pattern term info query needed as is currently only hitting the base query.

**Comment by Robbie1977** [comment]
See http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto for debug test version

**Comment by dosumis** [comment]
This is (I hope) no longer necessary. TermInfo generation should be as for any other class  I suspect the request for this arose from issues with term labels (in label addition & queries) that should now be fixed.  Please re-open if still an issue.
