### ISSUE TITLE
*Design and release new pub report & related queries*

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#51]
Minimal
1. Miniref  & Linkouts- FlyBase; PubMed; DOI - re-using  existing  pub=/xref code
2. Re-use existing query/results types:
  -  Datasets
  -  Anatomy - results as for regular anatomy query, but query consolidates def xrefs on FBbt + expression  curation.
   - Expression - results = all expression patterns (would be nice to have annotations to anat  here as  well but drop this for now  if too much work

**Comment by dosumis** [comment]
Direct info currently on Pub Nodes:

``` js
{
              "volume": "23",
              "iri": "http://flybase.org/reports/FBrf0221438",
              "pages": "644--655",
              "year": "2013",
              "short_form": "FBrf0221438",
              "label": "Ito et al., 2013, Curr. Biol. 23(8): 644--655",
              "title": "Systematic analysis of neural projections reveals clonal composition of the Drosophila brain.",
              "FlyBase": "FBrf0221438",
              "PMID": "23541729",
              "DOI": "10.1016/j.cub.2013.03.015",
              "miniref": "Ito et al., 2013, Curr. Biol. 23(8): 644--655"
 }
```

Core only captures label and and short_form

pub_return = core + PMID, DOI, FlyBase : WE REALLY NEED THESE ASAP!

To add:

Title  
Authors ? (would need to mine from FlyBase) 
Abstract? (would need to mine from FlyBase)

DataSets: can display - no need for query.  Display sample images too?
queries: anatomy; expression; phenotype (TBA).  Maybe combine these?

**Comment by mmc46** [comment]
Just came across the lack of a way to access the paper from the pub report. It would be really useful to add the minimal info.

Same as in an anatomical term report: external links using
```
"FlyBase": "FBrf0221438",
"PMID": "23541729",
"DOI": "10.1016/j.cub.2013.03.015"
```

**Comment by dosumis** [comment]
@Robbie1977  -  Would  this be OK?

```json
{
  "term": {
    "core": {
      "short_form": "FBrf0221438",
      "label": "Ito et al., 2013, Curr. Biol. 23(8): 644--655",
      "iri": "http://flybase.org/reports/FBrf0221438",
      "types": [
        "Individual",
        "pub",
        "Entity"
      ]
    },
    "description": [],
    "comment": []
  },
  "pub_links": {
    "PubMed": "23541729",
    "FlyBase": "FBrf0221438",
    "DOI": "10.1016/j.cub.2013.03.015"
  },
  "version": "e006860",
"title" : "Systematic analysis of neural projections reveals clonal composition of the Drosophila brain."
  "dataset_license": [
    {
      "term": {
        "core": {
          "short_form": "Ito2013",
          "label": "Ito lab adult brain lineage clone image set",
          "iri": "http://virtualflybrain.org/data/Ito2013",
          "types": [
            "Individual",
            "DataSet",
            "Entity"
          ]
        },
        "description": [
          "An exhaustive set of lineage clones covering the adult brain from Kei Ito\\'s  lab."
        ],
        "comment": []
      },
      "license": [
        {
          "icon": "http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png",
          "link": "https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode",
          "core": {
            "short_form": "VFBlicense_CC_BY_NC_SA_4_0",
            "label": "CC-BY-NC-SA_4.0",
            "iri": "http://creativecommons.org/licenses/by-nc-sa/4.0",
            "types": [
              "Individual",
              "License",
              "Entity"
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by dosumis** [comment]
Anat and expression reports can be queries from this.

I want to limit the number of permissible keys at the top level of the schema as proliferating this makes the schema confusing  to  consumers.  This only adds pub_links and title.

**Comment by dosumis** [comment]
@Robbie1977  - now fixed on branch according to above spec.  I'm still not completely comfortable with this.  Arbitrary extensions to the JSON schema at the top level that only apply to special cases look quite disorientating when presenting the schema for users  of the API/VFB_connect).  This is true of the `targeting_split` and `target_neurons` fields too.   I'm wondering  whether they should all get segregated under a generic primary key: `type_specific_content`.  @Robbie1977 - any opinion on this?
