### ISSUE TITLE
Modify image queries to return template and source.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#64]

**Comment by Robbie1977** [comment]
Existing OWL Class results list NEO query: https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/model/vfb.xmi#L168
Existing OWL Individual results ist NEO query: https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/model/vfb.xmi#L186
