### ISSUE TITLE
Related individuals bleeding through into relationships

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#88]
e.g. 

![image](https://user-images.githubusercontent.com/112839/98104969-21bb1f00-1e8f-11eb-91d4-f56f04eb4c3e.png)

This is because Relationships match clause lacks a class restriction on Object

```cql
OPTIONAL MATCH (o)<-[r {type:'Related'}]-($pvar$labels) 
```

**Comment by dosumis** [comment]
Fixed on pipeline 2. @Robbie1977 Can you update query?  (Remind me - do I need to dump the termInfo queries somewhere, or do you run that?

**Comment by Robbie1977** [comment]
I'll update that first thing tomorrow
